.PHONY: cppprime
cppprime:
	g++ -O3 -mavx2 -march=native primeanton.cpp -o primeanton
	g++ -O3 -mavx2 -march=native prime5versions.cpp -o primev5
	g++ -O3 -mavx2 -march=native supercomputerprime.cpp -o spprime

clean:
	rm primeanton
	rm spprime
	rm primev5