build:
	g++ -O3 -mavx2 -std=c++20 -march=native simplesieve.cpp -o simplesieve
	g++ -O3 -mavx2 -std=c++20 -march=native slowcomposite.cpp -o slowcomposite
	g++ -O3 -mavx2 -std=c++20 -march=native primeanton.cpp -o primeanton

clean:
	rm simplesieve
	rm slowcomposite
	rm primeanton